<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Street_Rod_AC</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>sr_ac.ico</ApplicationIcon>
    <Title>Street Rod AC Version</Title>
    <Description>A Street Rod version that runs on top of Asseto Corsa's core</Description>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AcTools">
      <HintPath>..\..\actools\Output\x64\Debug\AcTools.dll</HintPath>
    </Reference>
    <Reference Include="AcTools.Render">
      <HintPath>..\..\actools\Output\x64\Debug\AcTools.Render.dll</HintPath>
    </Reference>
    <Reference Include="SlimDX">
      <HintPath>..\..\actools\Libraries\SlimDX-x64\SlimDX.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2023.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\Backgrounds\*.png" />
    <Resource Include="Assets\Images\Buttons\*.png" />
    <Resource Include="Assets\Images\Icons\*.png" />
    <Resource Include="Assets\Images\UI\*.png" />
    <Resource Include="Assets\Images\Text\*.png" />
    <Resource Include="Assets\Images\Misc\*.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sr_ac.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Update="..\..\actools\Libraries\SlimDX-x64\SlimDX.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
